# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - cd crawler
    # You may remove this if you don't use go modules.
    # - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  id: crawler
  binary: crawlerbin
  dir: crawler
  main: ./main.go
  ldflags:
    - -s -w -X github.com/italia/developers-italia-backend/crawler/version.VERSION={{.Version}}
  env:
  - CGO_ENABLED=0
  hooks:
    post: cp crawler/config.toml.example {{ dir .Path }}/config.toml
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - crawlerbin
    builds:
      - crawler
    skip_push: false
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - crawler/config.toml.example
    image_templates:
      - "italia/developers-italia-backend:latest"
      - "italia/developers-italia-backend:{{ .Tag }}"
