version: "3.1"

networks:
  web:
    external:
      name: traefik_webgateway

services:
  elasticsearch:
    image: khezen/elasticsearch:6.2.2
    environment:
      - "CLUSTER_NAME=publiccode"
      - "ELASTIC_PWD=elastic"
      - "KIBANA_PWD=kibana"
      - "ES_TMPDIR=/tmp"
      - "HTTP_SSL=true"
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=elasticsearch'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:elasticsearch.${PROJECT_BASE_URL};Method:GET'
      - "traefik.frontend.auth.basic=elastic:$$2y$$12$$1oZ5vCDluxGnfV.ggxtvROITZnoQnWBuB8OeQu3CTt0TfUcP8XMJm"
      - "traefik.frontend.rateLimit.extractorFunc=client.ip"
      - "traefik.frontend.rateLimit.rateSet.elasticsearch.period=60s"
      - "traefik.frontend.rateLimit.rateSet.elasticsearch.average=100"
      - "traefik.frontend.rateLimit.rateSet.elasticsearch.burst=200"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - web
    volumes:
      - ./es_data:/elasticsearch/data

  kibana:
    image: khezen/kibana:6.2.2
    links:
      - elasticsearch
    environment:
      - "KIBANA_PWD=kibana"
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "ELASTICSEARCH_PORT=9200"
      - "KIBANA_HOST=0.0.0.0"
      - "ELASTICSEARCH_PROTOCOL=https"
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=kibana'
      - 'traefik.port=5601'
      - 'traefik.frontend.rule=Host:kibana.${PROJECT_BASE_URL}'
    ports:
      - "5601:5601"
    networks:
      - web
    volumes:
      - ./docker/images/kibana/config:/opt/kibana-6.2.2-linux-x86_64/config
      - ./docker/images/elasticsearch/config:/etc/elasticsearch

  prometheus:
    image: quay.io/prometheus/prometheus:v2.2.1
    labels:
      - 'traefik.backend=prometheus'
      - 'traefik.port=9090'
      - 'traefik.frontend.rule=Host:prometheus.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  spider:
    image: italia/developers-italia-backend:0.0.1
    networks:
      - web

 # #De comment next lines if you don't have Træfik running locally:
 #  proxy:
 #   command: --api --docker --docker.exposedByDefault=false --logLevel=DEBUG
 #   image: containous/traefik:experimental
 #   networks:
 #     - web
 #   ports:
 #     - "80:80"
 #     - "443:443"
 #     - "8080:8080"
 #   restart: always
 #   volumes:
 #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  es_data:
    driver: local
