version: "3.1"

networks:
  web:
    external:
      name: traefik_webgateway

services:
  elasticsearch:
    container_name: "${NAME}_elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      - "cluster.name=developers-italia"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.type=single-node"
    labels:
      - 'traefik.backend=elasticsearch'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:elasticsearch.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    container_name: "${NAME}_kibana"
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    environment:
      - "elasticsearch.url=http://elasticsearch:9200"
    labels:
      - 'traefik.backend=kibana'
      - 'traefik.port=5601'
      - 'traefik.frontend.rule=Host:kibana.${PROJECT_BASE_URL}'
    networks:
      - web

  prometheus:
    container_name: "${NAME}_prometheus"
    image: quay.io/prometheus/prometheus:v2.2.1
    labels:
      - 'traefik.backend=prometheus'
      - 'traefik.port=9090'
      - 'traefik.frontend.rule=Host:prometheus.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  crawler:
    container_name: "${NAME}_crawler"
    image: italia/developers-italia-backend:0.0.1
    networks:
      - web

volumes:
  es_data:
    driver: local
