version: "3.1"

services:
  elasticsearch:
    container_name: "${NAME}_elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      - "cluster.name=developers-italia"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.type=single-node"
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=elasticsearch'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:elasticsearch.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml

  kibana:
    container_name: "${NAME}_kibana"
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    environment:
      - "elasticsearch.url=http://elasticsearch:9200"
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=kibana'
      - 'traefik.port=5601'
      - 'traefik.frontend.rule=Host:kibana.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - ./docker/kibana/config/kibana.yml:/opt/kibana-6.2.2-linux-x86_64/config/kibana.yml

  prometheus:
    container_name: "${NAME}_prometheus"
    image: quay.io/prometheus/prometheus:v2.2.1
    labels:
      - "traefik.enable=true"
      - 'traefik.backend=prometheus'
      - 'traefik.port=9090'
      - 'traefik.frontend.rule=Host:prometheus.${PROJECT_BASE_URL}'
    networks:
      - web
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  proxy:
   command: --api --docker --docker.exposedByDefault=false --logLevel=DEBUG
   container_name: "${NAME}_proxy"
   image: containous/traefik:experimental
   networks:
     - web
   ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: "${NAME}_redis"
    image: redis:4.0
    networks:
      - web

  crawler:
    container_name: "${NAME}_crawler"
    image: italia/developers-italia-backend:0.0.1
    networks:
      - web
    volumes:
      - ./data:/app/data
      - ./whitelistGeneric.yml:/app/whitelistGeneric.yml
      - ./whitelistPA.yml:/app/whitelistPA.yml
      - ./domains.yml:/app/domains.yml
      - ./config.toml:/app/config.toml
      - ./jekyll/generated:/app/jekyll/generated


volumes:
  es_data:
    driver: local
