anchor_1: &job_defaults
  working_directory: /tmp/developers-italia-backend
  docker:
    - image: circleci/golang:1.13

version: 2
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout

      # Build
      - run: cd crawler && make build

      # Test
      - run: cd crawler && make test

      - persist_to_workspace:
          root: /tmp
          paths:
            - developers-italia-backend

workflows:
  version: 2
  build-test:
    jobs:
      - build
