elastic:
  hash: '$2y$12$aobnjSbn5LBZa/tam7nP/.PVItuVy/fq3FGvK8568XHA8HOAbFDIG' #elastic
  roles:
    - admin

kibana:
  hash: '$2y$12$a56HRA0WjN2E73fhtNKt/u6wdKPk.voutwmB8RDK.ZbAXHUBDlIUW' #kibana
  roles:
    - kibana_user

logstash:
  hash: '$2y$12$WXaYg0M81o.rQEBVP.Bcpet7wgqA4MZlrj1UuKKtOewLpXe3H90OW' #logstash
  roles:
    - logstash_user

beats:
  hash: '$2y$12$MVlAcLWHJXcMbB5fCSaPDO/t.N8G4XIFtEYrbulHpPpV5ewCuS6jS' #beats
  roles:
    - beats_user
