global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: developers-italia-backend
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - crawler:8081
